name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Install Deno ğŸ”„
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Build ğŸ› ï¸
        run: |
          deno run --allow-run --allow-read https://deno.land/x/snel/install.ts
          trex run build
      - name: Upload Site Artifacts ğŸ”º
        uses: actions/upload-artifact@v1
        with:
          name: site
          path: dist
      - name: Upload Static Artifacts ğŸ”º
        uses: actions/upload-artifact@v1
        with:
          name: static
          path: public/guns-n-goose/static

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
      - name: Download Site Artifacts ğŸ”»
        uses: actions/download-artifact@v1
        with:
          name: site
      - name: Download Static Artifacts ğŸ”»
        uses: actions/download-artifact@v1
        with:
          name: static
      - name: Create and move files â•
        run: |
          mkdir site/static
          mv static/* site/static
          cp site/index.html site/404.html
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: "site"
